documentation: 
- changed-files:
  - any-glob-to-any-file: 'readme.mustache'
images: 
- changed-files:
  - any-glob-to-any-file: 'plane_images.csv'
ukraine: 
- changed-files:
  - any-glob-to-any-file: 'plane-alert-ukraine.csv'
planes:
- changed-files:
  - any-glob-to-any-file: '*.csv' 
  - all-globs-to-all-files: '!plane_images.csv'
  
