name: Create and commit category, images and extended database files

on:
  push:
    branches: ["automation"]
    paths:
      - "plane-alert-db.csv"
      - "plane_images.txt"
      - "blacklist.txt"

jobs:
  createDerivativeDatabases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r ./scripts/requirements.txt

      - name: Create category, images and extended database CSV files
        run: python ./scripts/create_db_derivatives.py

      - name: Commit category, images and extended database CSV files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: update derivative databases."
